### ISSUE TITLE
Pytanie dotyczące bazy MySQL

### ISSUE THREAD

**Issue by SlimaKCoder** [NorthPL/LogIt#1]
Czy podałbyś strukturę bazy danych MySQL, potrzebuje jej do pracy nad integracją LogIt z kodem PHP, przy okazji jakbyś miał jakąś bazę LogIt z testowymi danymi to również byłbym wdzięczny :)

**Comment by NorthPL** [comment]
http://northpl.tk/logit.sql
Dla konta NorthPL93 hasło to 123456789 (użytkownik był raz na serwerze)
Dla konta test hasło to test (użytkownika nigdy nie było na serwerze - zarejestrowany z konsoli)

Hasło jest (chyba)domyślnie hasowane tak: sha-256(hasło+sól)
https://github.com/NorthPL/LogIt/blob/master/src/main/java/io/github/lucaseasedup/logit/security/SecurityHelper.java#L338
